In [39]:
import numpy as np

In [40]:
a = np.array([1, 3, 5, 1, 3]) #создадим три одномерных массива
b = np.arange(1, 6)  
c = np.ones(5)
a, b, c

(array([1, 3, 5, 1, 3]), array([1, 2, 3, 4, 5]), array([1., 1., 1., 1., 1.]))

In [41]:
print(a.shape, b.shape, c.shape) #выводим атрибуты массивов (размерность, число осей, тип данных)
print(a.ndim, b.ndim, c.ndim)
print(a.dtype, b.dtype, c.dtype)

(5,) (5,) (5,)
1 1 1
int64 int64 float64


In [42]:
print(a[::2]) #выводим массив с шагом 2
print(b[:3])  #выводим подмассив, от начала до 3 элемента невключительно 
print(c[-1])  #выводим последний элемент

[1 5 3]
[1 2 3]
1.0


In [43]:
print(a*b) #поэлементное умножение
print(a.sum() + b.sum() + c.sum()) #сумма всех элементов массивов

[ 1  6 15  4 15]
33.0


In [44]:
d = np.array([[1, 2, 3], #создадим два двумерных массивов
              [4, 5, 6],
              [7, 8, 9]])

e = np.eye(3)
d, e

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [45]:
print(np.transpose(d)) #транспонированная матрица

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [46]:
print(np.dot(d, e)) #матричное умножение

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [47]:
print(d.min() + e.max()) #сумма миннимального и максимального элементов массивов

2.0
